name: upload-static-files

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: upload to s3 bucket
        uses: noelware/s3-action@2
        with:
          directories: './functions/public'
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_SECRET_KEY }}
          bucket: ${{ secrets.S3_BUCKET_NAME }}
